name = "TestModule"
uuid = "d3bdda09-00fc-48a2-85f7-f77a9dc3353b"
authors = ["CasperCamenisch <camenisch.casper@outlook.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
